const fs = require('fs');

const phrases = [
  "自然景观点",
  "评分 4.8/5（Google）",
  "24 小时开放",
  "面向英吉利海峡的",
  "纪念碑级拱门",
  "Falaise d’Aval 是 Étretat 最具辨识度的海崖段之一：白垩悬崖被海水雕刻出巨大的天然拱门（Porte d’Aval），旁侧可见“针状岩”（L’Aiguille）。低潮时更靠近礁滩与洞穴区域，但涨潮速度快——请把潮汐当作第一条规则。",
  "开始了解",
  "看照片",
  "位置",
  "关键词",
  "拱门 / 针状岩 / 低潮 / 观景步道",
  "为什么这里最‘像Étretat’",
  "一眼识别的拱门轮廓 + 近距离可触达的海蚀地形，让 Falaise d’Aval 成为经典观景点。",
  "海蚀拱门像一座天然“门洞”，在不同光线下呈现完全不同的层次。",
  "“针状岩”立在海中，是摄影构图里的稳定锚点：广角看尺度，长焦看纹理。",
  "低潮可达",
  "许多近景视角只在低潮窗口出现；涨潮会迅速抹掉路径。安全第一。",
  "说明：页面基础信息（评分、开放时间、Plus Code）来自 Google Maps；地貌与观景建议参考公开旅游信息。",
  "怎么逛更舒服",
  "这里的关键不是‘走多远’，而是‘什么时候走’：低潮窗口 + 回撤余量。",
  "半日路线（不赶）",
  "海滩侧先取一个‘远景点’",
  "先用远景确定拱门、针状岩、浪线关系，再决定是否近距离探索。",
  "低潮窗口进入礁滩（可选）",
  "只在你确定潮汐与退路时进入；不要把‘拍到’建立在‘赌一把’上。",
  "上崖顶步道看轮廓与光线",
  "崖顶更适合全景与日落光；风大时注意站位与边缘距离。",
  "潮汐提醒",
  "谷地/礁滩区域一旦涨潮，很容易被海水“切断”回程。最稳妥：",
  "只在低潮窗口进入",
  "，并预留至少 1 小时回撤。",
  "鞋子与步行",
  "鹅卵石路面更费力且更滑，建议穿防滑鞋；摄影党最好带长焦与防风外套。",
  "在 Google Maps 里规划路线",
  "自然景观点；部分近景路线受潮汐/天气影响。",
  "日落前后",
  "逆光或侧逆光会强调悬崖纹理；阴天则更适合拍“冷色电影感”。",
  "远离边缘",
  "崖顶风强且边缘松散，请保持距离；拍照时更不要背对海风走近边缘。",
  "数据与引用",
  "为了保持信息可信，我们只引用可公开访问的页面。",
  "Google Maps（地点基础信息）",
  "评分、开放时间、Plus Code、简介等（可能随时间变化）",
  "打开",
  "参考站点：plagedetretat.com",
  "版式节奏与栏目结构参考（非内容复制）",
  "阴天质感：Porte d’Aval 的拱门",
  "海滩视角：拱门与海浪",
  "暮色与低潮礁滩的层次",
  "悬崖步道俯瞰：Aiguille 与海湾",
  "Falaise d’Aval、Porte d’Aval 与 L’Aiguille"
];

const translations = {
  fr: {
    "自然景观点": "Site naturel",
    "评分 4.8/5（Google）": "Note 4.8/5 (Google)",
    "24 小时开放": "Ouvert 24h/24",
    "面向英吉利海峡的": "Face à la Manche",
    "纪念碑级拱门": "Arche monumentale",
    "Falaise d’Aval 是 Étretat 最具辨识度的海崖段之一：白垩悬崖被海水雕刻出巨大的天然拱门（Porte d’Aval），旁侧可见“针状岩”（L’Aiguille）。低潮时更靠近礁滩与洞穴区域，但涨潮速度快——请把潮汐当作第一条规则。": "La Falaise d’Aval est l'une des sections les plus reconnaissables d'Étretat : la falaise de craie a été sculptée par la mer en une immense arche naturelle (Porte d’Aval), flanquée de l'Aiguille. À marée basse, vous pouvez vous approcher des récifs et des grottes, mais la marée monte vite — considérez les marées comme la règle numéro un.",
    "开始了解": "Découvrir",
    "看照片": "Voir les photos",
    "位置": "Lieu",
    "关键词": "Mots-clés",
    "拱门 / 针状岩 / 低潮 / 观景步道": "Arche / Aiguille / Marée basse / Sentier",
    "为什么这里最‘像Étretat’": "Pourquoi c'est l'essence d'Étretat",
    "一眼识别的拱门轮廓 + 近距离可触达的海蚀地形，让 Falaise d’Aval 成为经典观景点。": "La silhouette de l'arche instantanément reconnaissable combinée au relief d'érosion marine accessible de près fait de la Falaise d’Aval un point de vue classique.",
    "海蚀拱门像一座天然“门洞”，在不同光线下呈现完全不同的层次。": "L'arche d'érosion marine ressemble à une « porte » naturelle, présentant des couches complètement différentes selon la lumière.",
    "“针状岩”立在海中，是摄影构图里的稳定锚点：广角看尺度，长焦看纹理。": "L'« Aiguille » se dresse dans la mer, un point d'ancrage stable pour la composition photographique : le grand angle pour l'échelle, le téléobjectif pour la texture.",
    "低潮可达": "Accessible à marée basse",
    "许多近景视角只在低潮窗口出现；涨潮会迅速抹掉路径。安全第一。": "De nombreuses vues rapprochées n'apparaissent qu'à marée basse ; la marée montante effacera rapidement le chemin. La sécurité d'abord.",
    "说明：页面基础信息（评分、开放时间、Plus Code）来自 Google Maps；地貌与观景建议参考公开旅游信息。": "Remarque : Les informations de base de la page (note, heures d'ouverture, Plus Code) proviennent de Google Maps ; les suggestions de relief et d'observation sont basées sur des informations touristiques publiques.",
    "怎么逛更舒服": "Comment visiter confortablement",
    "这里的关键不是‘走多远’，而是‘什么时候走’：低潮窗口 + 回撤余量。": "La clé ici n'est pas « jusqu'où aller », mais « quand y aller » : fenêtre de marée basse + marge de retour.",
    "半日路线（不赶）": "Itinéraire d'une demi-journée (détendu)",
    "海滩侧先取一个‘远景点’": "Prenez d'abord un point de vue éloigné du côté de la plage",
    "先用远景确定拱门、针状岩、浪线关系，再决定是否近距离探索。": "Utilisez d'abord la vue lointaine pour déterminer la relation entre l'arche, l'aiguille et la ligne de vagues, puis décidez d'explorer de plus près.",
    "低潮窗口进入礁滩（可选）": "Entrez sur le récif pendant la fenêtre de marée basse (facultatif)",
    "只在你确定潮汐与退路时进入；不要把‘拍到’建立在‘赌一把’上。": "N'entrez que si vous êtes sûr de la marée et de la voie de retraite ; ne pariez pas votre sécurité pour une photo.",
    "上崖顶步道看轮廓与光线": "Montez sur le sentier au sommet de la falaise pour voir les contours et la lumière",
    "崖顶更适合全景与日落光；风大时注意站位与边缘距离。": "Le sommet de la falaise est plus adapté aux vues panoramiques et à la lumière du coucher du soleil ; faites attention à votre position et à la distance du bord lorsqu'il y a du vent.",
    "潮汐提醒": "Rappel des marées",
    "谷地/礁滩区域一旦涨潮，很容易被海水“切断”回程。最稳妥：": "Une fois que la marée monte, la zone de vallée/récif peut facilement vous « couper » du retour. Le plus sûr :",
    "只在低潮窗口进入": "n'entrez que pendant la fenêtre de marée basse",
    "，并预留至少 1 小时回撤。": ", et prévoyez au moins 1 heure pour le retour.",
    "鞋子与步行": "Chaussures et marche",
    "鹅卵石路面更费力且更滑，建议穿防滑鞋；摄影党最好带长焦与防风外套。": "Les routes de galets sont plus fatigantes et glissantes, il est recommandé de porter des chaussures antidérapantes ; les photographes devraient apporter un téléobjectif et une veste coupe-vent.",
    "在 Google Maps 里规划路线": "Planifier l'itinéraire dans Google Maps",
    "自然景观点；部分近景路线受潮汐/天气影响。": "Site naturel ; certains itinéraires de vue rapprochée sont affectés par les marées/la météo.",
    "日落前后": "Autour du coucher du soleil",
    "逆光或侧逆光会强调悬崖纹理；阴天则更适合拍“冷色电影感”。": "Le contre-jour ou le contre-jour latéral soulignera la texture de la falaise ; les jours nuageux conviennent mieux à une ambiance cinématographique aux tons froids.",
    "远离边缘": "Restez à l'écart du bord",
    "崖顶风强且边缘松散，请保持距离；拍照时更不要背对海风走近边缘。": "Le vent au sommet de la falaise est fort et le bord est meuble, veuillez garder vos distances ; ne vous approchez pas du bord le dos tourné au vent de mer pour prendre des photos.",
    "数据与引用": "Données et citations",
    "为了保持信息可信，我们只引用可公开访问的页面。": "Afin de maintenir la crédibilité des informations, nous ne citons que des pages accessibles au public.",
    "Google Maps（地点基础信息）": "Google Maps (Informations de base sur le lieu)",
    "评分、开放时间、Plus Code、简介等（可能随时间变化）": "Note, heures d'ouverture, Plus Code, introduction, etc. (susceptibles de changer avec le temps)",
    "打开": "Ouvrir",
    "参考站点：plagedetretat.com": "Site de référence : plagedetretat.com",
    "版式节奏与栏目结构参考（非内容复制）": "Rythme de mise en page et référence de structure de colonne (pas de copie de contenu)",
    "阴天质感：Porte d’Aval 的拱门": "Texture nuageuse : L'arche de la Porte d’Aval",
    "海滩视角：拱门与海浪": "Vue de la plage : Arche et vagues",
    "暮色与低潮礁滩的层次": "Crépuscule et strates du récif à marée basse",
    "悬崖步道俯瞰：Aiguille 与海湾": "Vue depuis le sentier de la falaise : L'Aiguille et la baie",
    "Falaise d’Aval、Porte d’Aval 与 L’Aiguille": "Falaise d’Aval, Porte d’Aval et L’Aiguille"
  },
  en: {
    "自然景观点": "Natural Landmark",
    "评分 4.8/5（Google）": "Rating 4.8/5 (Google)",
    "24 小时开放": "Open 24/7",
    "面向英吉利海峡的": "Facing the English Channel",
    "纪念碑级拱门": "Monumental Arch",
    "Falaise d’Aval 是 Étretat 最具辨识度的海崖段之一：白垩悬崖被海水雕刻出巨大的天然拱门（Porte d’Aval），旁侧可见“针状岩”（L’Aiguille）。低潮时更靠近礁滩与洞穴区域，但涨潮速度快——请把潮汐当作第一条规则。": "Falaise d’Aval is one of Étretat's most recognizable cliff sections: the chalk cliff carved by the sea into a huge natural arch (Porte d’Aval), flanked by the 'Needle' (L’Aiguille). At low tide, you can get closer to the reefs and caves, but the tide comes in fast — treat tides as the number one rule.",
    "开始了解": "Get Started",
    "看照片": "View Photos",
    "位置": "Location",
    "关键词": "Keywords",
    "拱门 / 针状岩 / 低潮 / 观景步道": "Arch / Needle / Low Tide / Trail",
    "为什么这里最‘像Étretat’": "Why it's the essence of Étretat",
    "一眼识别的拱门轮廓 + 近距离可触达的海蚀地形，让 Falaise d’Aval 成为经典观景点。": "The instantly recognizable arch silhouette combined with closely accessible marine erosion terrain makes Falaise d’Aval a classic viewpoint.",
    "海蚀拱门像一座天然“门洞”，在不同光线下呈现完全不同的层次。": "The marine erosion arch is like a natural 'doorway', presenting completely different layers under different lighting.",
    "“针状岩”立在海中，是摄影构图里的稳定锚点：广角看尺度，长焦看纹理。": "The 'Needle' stands in the sea, a stable anchor point in photographic composition: wide-angle for scale, telephoto for texture.",
    "低潮可达": "Accessible at Low Tide",
    "许多近景视角只在低潮窗口出现；涨潮会迅速抹掉路径。安全第一。": "Many close-up views only appear during the low tide window; the rising tide will quickly wipe out the path. Safety first.",
    "说明：页面基础信息（评分、开放时间、Plus Code）来自 Google Maps；地貌与观景建议参考公开旅游信息。": "Note: Basic page information (rating, opening hours, Plus Code) is from Google Maps; landform and viewing suggestions refer to public tourist information.",
    "怎么逛更舒服": "How to visit comfortably",
    "这里的关键不是‘走多远’，而是‘什么时候走’：低潮窗口 + 回撤余量。": "The key here is not 'how far to go', but 'when to go': low tide window + return margin.",
    "半日路线（不赶）": "Half-day route (relaxed)",
    "海滩侧先取一个‘远景点’": "First take a distant view from the beach side",
    "先用远景确定拱门、针状岩、浪线关系，再决定是否近距离探索。": "First use the distant view to determine the relationship between the arch, needle, and wave line, then decide whether to explore up close.",
    "低潮窗口进入礁滩（可选）": "Enter the reef during low tide window (optional)",
    "只在你确定潮汐与退路时进入；不要把‘拍到’建立在‘赌一把’上。": "Only enter when you are sure of the tide and retreat path; don't gamble your safety for a photo.",
    "上崖顶步道看轮廓与光线": "Go up the cliff top trail to see contours and light",
    "崖顶更适合全景与日落光；风大时注意站位与边缘距离。": "The cliff top is more suitable for panoramic views and sunset light; pay attention to your position and edge distance when it's windy.",
    "潮汐提醒": "Tide Reminder",
    "谷地/礁滩区域一旦涨潮，很容易被海水“切断”回程。最稳妥：": "Once the tide rises, the valley/reef area can easily 'cut off' your return. Safest:",
    "只在低潮窗口进入": "only enter during low tide window",
    "，并预留至少 1 小时回撤。": ", and leave at least 1 hour for return.",
    "鞋子与步行": "Shoes and Walking",
    "鹅卵石路面更费力且更滑，建议穿防滑鞋；摄影党最好带长焦与防风外套。": "Pebble roads are more strenuous and slippery, non-slip shoes are recommended; photographers should bring a telephoto lens and windbreaker.",
    "在 Google Maps 里规划路线": "Plan route in Google Maps",
    "自然景观点；部分近景路线受潮汐/天气影响。": "Natural viewpoint; some close-up routes are affected by tides/weather.",
    "日落前后": "Around Sunset",
    "逆光或侧逆光会强调悬崖纹理；阴天则更适合拍“冷色电影感”。": "Backlight or side backlight will emphasize cliff texture; cloudy days are better for a cold-toned cinematic feel.",
    "远离边缘": "Stay Away from Edge",
    "崖顶风强且边缘松散，请保持距离；拍照时更不要背对海风走近边缘。": "Cliff top winds are strong and edges are loose, please keep your distance; do not approach the edge with your back to the sea wind when taking photos.",
    "数据与引用": "Data and Citations",
    "为了保持信息可信，我们只引用可公开访问的页面。": "In order to maintain credible information, we only cite publicly accessible pages.",
    "Google Maps（地点基础信息）": "Google Maps (Basic location info)",
    "评分、开放时间、Plus Code、简介等（可能随时间变化）": "Rating, opening hours, Plus Code, intro, etc. (may change over time)",
    "打开": "Open",
    "参考站点：plagedetretat.com": "Reference site: plagedetretat.com",
    "版式节奏与栏目结构参考（非内容复制）": "Layout rhythm and column structure reference (not content copy)",
    "阴天质感：Porte d’Aval 的拱门": "Cloudy texture: Arch of Porte d’Aval",
    "海滩视角：拱门与海浪": "Beach view: Arch and waves",
    "暮色与低潮礁滩的层次": "Twilight and layers of low tide reef",
    "悬崖步道俯瞰：Aiguille 与海湾": "Cliff trail overlook: Aiguille and bay",
    "Falaise d’Aval、Porte d’Aval 与 L’Aiguille": "Falaise d’Aval, Porte d’Aval and L’Aiguille"
  },
  "zh-Hant": {
    "自然景观点": "自然景觀點",
    "评分 4.8/5（Google）": "評分 4.8/5（Google）",
    "24 小时开放": "24 小時開放",
    "面向英吉利海峡的": "面向英吉利海峽的",
    "纪念碑级拱门": "紀念碑級拱門",
    "Falaise d’Aval 是 Étretat 最具辨识度的海崖段之一：白垩悬崖被海水雕刻出巨大的天然拱门（Porte d’Aval），旁侧可见“针状岩”（L’Aiguille）。低潮时更靠近礁滩与洞穴区域，但涨潮速度快——请把潮汐当作第一条规则。": "Falaise d’Aval 是 Étretat 最具辨識度的海崖段之一：白堊懸崖被海水雕刻出巨大的天然拱門（Porte d’Aval），旁側可見“針狀岩”（L’Aiguille）。低潮時更靠近礁灘與洞穴區域，但漲潮速度快——請把潮汐當作第一條規則。",
    "开始了解": "開始了解",
    "看照片": "看照片",
    "位置": "位置",
    "关键词": "關鍵詞",
    "拱门 / 针状岩 / 低潮 / 观景步道": "拱門 / 針狀岩 / 低潮 / 觀景步道",
    "为什么这里最‘像Étretat’": "為什麼這裡最‘像Étretat’",
    "一眼识别的拱门轮廓 + 近距离可触达的海蚀地形，让 Falaise d’Aval 成为经典观景点。": "一眼識別的拱門輪廓 + 近距離可觸達的海蝕地形，讓 Falaise d’Aval 成為經典觀景點。",
    "海蚀拱门像一座天然“门洞”，在不同光线下呈现完全不同的层次。": "海蝕拱門像一座天然“門洞”，在不同光線下呈現完全不同的層次。",
    "“针状岩”立在海中，是摄影构图里的稳定锚点：广角看尺度，长焦看纹理。": "“針狀岩”立在海中，是攝影構圖裡的穩定錨點：廣角看尺度，長焦看紋理。",
    "低潮可达": "低潮可達",
    "许多近景视角只在低潮窗口出现；涨潮会迅速抹掉路径。安全第一。": "許多近景視角只在低潮窗口出現；漲潮會迅速抹掉路徑。安全第一。",
    "说明：页面基础信息（评分、开放时间、Plus Code）来自 Google Maps；地貌与观景建议参考公开旅游信息。": "說明：頁面基礎信息（評分、開放時間、Plus Code）來自 Google Maps；地貌與觀景建議參考公開旅遊信息。",
    "怎么逛更舒服": "怎麼逛更舒服",
    "这里的关键不是‘走多远’，而是‘什么时候走’：低潮窗口 + 回撤余量。": "這裡的關鍵不是‘走多遠’，而是‘什麼時候走’：低潮窗口 + 回撤餘量。",
    "半日路线（不赶）": "半日路線（不趕）",
    "海滩侧先取一个‘远景点’": "海灘側先取一個‘遠景點’",
    "先用远景确定拱门、针状岩、浪线关系，再决定是否近距离探索。": "先用遠景確定拱門、針狀岩、浪線關係，再決定是否近距離探索。",
    "低潮窗口进入礁滩（可选）": "低潮窗口進入礁灘（可選）",
    "只在你确定潮汐与退路时进入；不要把‘拍到’建立在‘赌一把’上。": "只在你確定潮汐與退路時進入；不要把‘拍到’建立在‘賭一把’上。",
    "上崖顶步道看轮廓与光线": "上崖頂步道看輪廓與光線",
    "崖顶更适合全景与日落光；风大时注意站位与边缘距离。": "崖頂更適合全景與日落光；風大時注意站位與邊緣距離。",
    "潮汐提醒": "潮汐提醒",
    "谷地/礁滩区域一旦涨潮，很容易被海水“切断”回程。最稳妥：": "谷地/礁灘區域一旦漲潮，很容易被海水“切斷”回程。最穩妥：",
    "只在低潮窗口进入": "只在低潮窗口進入",
    "，并预留至少 1 小时回撤。": "，並預留至少 1 小時回撤。",
    "鞋子与步行": "鞋子與步行",
    "鹅卵石路面更费力且更滑，建议穿防滑鞋；摄影党最好带长焦与防风外套。": "鵝卵石路面更費力且更滑，建議穿防滑鞋；攝影黨最好帶長焦與防風外套。",
    "在 Google Maps 里规划路线": "在 Google Maps 裡規劃路線",
    "自然景观点；部分近景路线受潮汐/天气影响。": "自然景觀點；部分近景路線受潮汐/天氣影響。",
    "日落前后": "日落前後",
    "逆光或侧逆光会强调悬崖纹理；阴天则更适合拍“冷色电影感”。": "逆光或側逆光會強調懸崖紋理；陰天則更適合拍“冷色電影感”。",
    "远离边缘": "遠離邊緣",
    "崖顶风强且边缘松散，请保持距离；拍照时更不要背对海风走近边缘。": "崖頂風強且邊緣鬆散，請保持距離；拍照時更不要背對海風走近邊緣。",
    "数据与引用": "數據與引用",
    "为了保持信息可信，我们只引用可公开访问的页面。": "為了保持信息可信，我們只引用可公開訪問的頁面。",
    "Google Maps（地点基础信息）": "Google Maps（地點基礎信息）",
    "评分、开放时间、Plus Code、简介等（可能随时间变化）": "評分、開放時間、Plus Code、簡介等（可能隨時間變化）",
    "打开": "打開",
    "参考站点：plagedetretat.com": "參考站點：plagedetretat.com",
    "版式节奏与栏目结构参考（非内容复制）": "版式節奏與欄目結構參考（非內容複製）",
    "阴天质感：Porte d’Aval 的拱门": "陰天質感：Porte d’Aval 的拱門",
    "海滩视角：拱门与海浪": "海灘視角：拱門與海浪",
    "暮色与低潮礁滩的层次": "暮色與低潮礁灘的層次",
    "悬崖步道俯瞰：Aiguille 与海湾": "懸崖步道俯瞰：Aiguille 與海灣",
    "Falaise d’Aval、Porte d’Aval 与 L’Aiguille": "Falaise d’Aval、Porte d’Aval 與 L’Aiguille"
  },
  de: {
    "自然景观点": "Naturdenkmal",
    "评分 4.8/5（Google）": "Bewertung 4.8/5 (Google)",
    "24 小时开放": "24/7 geöffnet",
    "面向英吉利海峡的": "Mit Blick auf den Ärmelkanal",
    "纪念碑级拱门": "Monumentaler Bogen",
    "Falaise d’Aval 是 Étretat 最具辨识度的海崖段之一：白垩悬崖被海水雕刻出巨大的天然拱门（Porte d’Aval），旁侧可见“针状岩”（L’Aiguille）。低潮时更靠近礁滩与洞穴区域，但涨潮速度快——请把潮汐当作第一条规则。": "Die Falaise d’Aval ist einer der bekanntesten Klippenabschnitte von Étretat: Die Kreideklippe wurde vom Meer zu einem riesigen natürlichen Bogen (Porte d’Aval) geformt, flankiert von der 'Nadel' (L’Aiguille). Bei Ebbe können Sie sich den Riffen und Höhlen nähern, aber die Flut kommt schnell — betrachten Sie die Gezeiten als Regel Nummer eins.",
    "开始了解": "Mehr erfahren",
    "看照片": "Fotos ansehen",
    "位置": "Ort",
    "关键词": "Schlüsselwörter",
    "拱门 / 针状岩 / 低潮 / 观景步道": "Bogen / Nadel / Ebbe / Wanderweg",
    "为什么这里最‘像Étretat’": "Warum es die Essenz von Étretat ist",
    "一眼识别的拱门轮廓 + 近距离可触达的海蚀地形，让 Falaise d’Aval 成为经典观景点。": "Die sofort erkennbare Bogensilhouette in Kombination mit dem hautnah erlebbaren Meereserosionsgelände macht die Falaise d’Aval zu einem klassischen Aussichtspunkt.",
    "海蚀拱门像一座天然“门洞”，在不同光线下呈现完全不同的层次。": "Der Meereserosionsbogen ist wie ein natürliches 'Tor', das unter verschiedenen Lichtverhältnissen völlig unterschiedliche Schichten präsentiert.",
    "“针状岩”立在海中，是摄影构图里的稳定锚点：广角看尺度，长焦看纹理。": "Die 'Nadel' steht im Meer, ein stabiler Ankerpunkt in der fotografischen Komposition: Weitwinkel für den Maßstab, Teleobjektiv für die Textur.",
    "低潮可达": "Zugänglich bei Ebbe",
    "许多近景视角只在低潮窗口出现；涨潮会迅速抹掉路径。安全第一。": "Viele Nahansichten erscheinen nur während des Ebbefensters; die Flut wird den Weg schnell auslöschen. Sicherheit zuerst.",
    "说明：页面基础信息（评分、开放时间、Plus Code）来自 Google Maps；地貌与观景建议参考公开旅游信息。": "Hinweis: Grundlegende Seiteninformationen (Bewertung, Öffnungszeiten, Plus Code) stammen von Google Maps; Landform- und Beobachtungsvorschläge beziehen sich auf öffentliche Touristeninformationen.",
    "怎么逛更舒服": "Wie man bequem besucht",
    "这里的关键不是‘走多远’，而是‘什么时候走’：低潮窗口 + 回撤余量。": "Der Schlüssel hier ist nicht 'wie weit man geht', sondern 'wann man geht': Ebbefenster + Rückkehrmarge.",
    "半日路线（不赶）": "Halbtagesroute (entspannt)",
    "海滩侧先取一个‘远景点’": "Nehmen Sie zuerst einen fernen Blick von der Strandseite",
    "先用远景确定拱门、针状岩、浪线关系，再决定是否近距离探索。": "Verwenden Sie zuerst die Fernsicht, um die Beziehung zwischen Bogen, Nadel und Wellenlinie zu bestimmen, und entscheiden Sie dann, ob Sie aus der Nähe erkunden möchten.",
    "低潮窗口进入礁滩（可选）": "Betreten Sie das Riff während des Ebbefensters (optional)",
    "只在你确定潮汐与退路时进入；不要把‘拍到’建立在‘赌一把’上。": "Treten Sie nur ein, wenn Sie sich der Gezeiten und des Rückzugsweges sicher sind; spielen Sie nicht mit Ihrer Sicherheit für ein Foto.",
    "上崖顶步道看轮廓与光线": "Gehen Sie den Pfad auf der Klippe hinauf, um Konturen und Licht zu sehen",
    "崖顶更适合全景与日落光；风大时注意站位与边缘距离。": "Der Gipfel der Klippe eignet sich besser für Panoramablicke und Sonnenuntergangslicht; achten Sie bei Wind auf Ihre Position und den Abstand zum Rand.",
    "潮汐提醒": "Gezeitenerinnerung",
    "谷地/礁滩区域一旦涨潮，很容易被海水“切断”回程。最稳妥：": "Sobald die Flut steigt, kann das Tal-/Riffgebiet Sie leicht von der Rückkehr 'abschneiden'. Am sichersten:",
    "只在低潮窗口进入": "nur während des Ebbefensters betreten",
    "，并预留至少 1 小时回撤。": ", und lassen Sie mindestens 1 Stunde für die Rückkehr.",
    "鞋子与步行": "Schuhe und Gehen",
    "鹅卵石路面更费力且更滑，建议穿防滑鞋；摄影党最好带长焦与防风外套。": "Kieselstraßen sind anstrengender und rutschiger, rutschfeste Schuhe werden empfohlen; Fotografen sollten ein Teleobjektiv und eine Windjacke mitbringen.",
    "在 Google Maps 里规划路线": "Route in Google Maps planen",
    "自然景观点；部分近景路线受潮汐/天气影响。": "Naturdenkmal; einige Nahansichtsrouten werden von Gezeiten/Wetter beeinflusst.",
    "日落前后": "Rund um den Sonnenuntergang",
    "逆光或侧逆光会强调悬崖纹理；阴天则更适合拍“冷色电影感”。": "Gegenlicht oder seitliches Gegenlicht betonen die Klippentextur; bewölkte Tage eignen sich besser für ein kaltes kinoreifes Gefühl.",
    "远离边缘": "Bleiben Sie vom Rand fern",
    "崖顶风强且边缘松散，请保持距离；拍照时更不要背对海风走近边缘。": "Der Wind auf der Klippe ist stark und die Ränder sind lose, bitte halten Sie Abstand; nähern Sie sich dem Rand beim Fotografieren nicht mit dem Rücken zum Seewind.",
    "数据与引用": "Daten und Zitate",
    "为了保持信息可信，我们只引用可公开访问的页面。": "Um die Glaubwürdigkeit der Informationen zu wahren, zitieren wir nur öffentlich zugängliche Seiten.",
    "Google Maps（地点基础信息）": "Google Maps (Grundlegende Standortinformationen)",
    "评分、开放时间、Plus Code、简介等（可能随时间变化）": "Bewertung, Öffnungszeiten, Plus Code, Einführung usw. (können sich im Laufe der Zeit ändern)",
    "打开": "Öffnen",
    "参考站点：plagedetretat.com": "Referenzseite: plagedetretat.com",
    "版式节奏与栏目结构参考（非内容复制）": "Layout-Rhythmus und Spaltenstruktur-Referenz (keine Inhaltskopie)",
    "阴天质感：Porte d’Aval 的拱门": "Bewölkte Textur: Bogen der Porte d’Aval",
    "海滩视角：拱门与海浪": "Strandblick: Bogen und Wellen",
    "暮色与低潮礁滩的层次": "Dämmerung und Schichten des Riffs bei Ebbe",
    "悬崖步道俯瞰：Aiguille 与海湾": "Blick vom Klippenpfad: Aiguille und Bucht",
    "Falaise d’Aval、Porte d’Aval 与 L’Aiguille": "Falaise d’Aval, Porte d’Aval und L’Aiguille"
  }
};

let content = fs.readFileSync('src/i18n.ts', 'utf8');

for (const lng in translations) {
  let toInsert = '';
  for (const [key, val] of Object.entries(translations[lng])) {
    const safeKey = key.replace(/"/g, '\\"');
    const safeVal = val.replace(/"/g, '\\"');
    if (!content.includes('"' + safeKey + '"')) {
      toInsert += '      "' + safeKey + '": "' + safeVal + '",\n';
    }
  }
  if (toInsert) {
    const targetCount = lng === 'fr' ? 1 : lng === 'en' ? 2 : lng === 'zh-Hant' ? 3 : 4;
    let matchCount = 0;
    content = content.replace(/([ \t]*"隐私政策")/g, (match, p1) => {
      matchCount++;
      if (matchCount === targetCount) {
        return toInsert + p1;
      }
      return match;
    });
  }
}

fs.writeFileSync('src/i18n.ts', content, 'utf8');

// Now replace in Home.tsx
let homeContent = fs.readFileSync('src/pages/Home.tsx', 'utf8');
phrases.forEach(phrase => {
  // text inside tags like <div>中文</div> -> <div>{t("中文")}</div>
  const regexContent = new RegExp(`(>[\\s\\n]*)(${phrase})([\\s\\n]*<)`, 'g');
  homeContent = homeContent.replace(regexContent, `$1{t("${phrase}")}$3`);
});

fs.writeFileSync('src/pages/Home.tsx', homeContent, 'utf8');
console.log('Replaced all');
